
services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=modulo
      - POSTGRES_PASSWORD=modulo
      - POSTGRES_DB=task
    ports:
      - '5432:5432'

  taskfe:
    container_name: taskfe
    build:
      context: ../../frontend/taskfe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  task:
    container_name: task
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/task
      - SPRING_DATASOURCE_USERNAME=modulo
      - SPRING_DATASOURCE_PASSWORD=modulo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_started
